jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 240
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack:
        BUILD: stack
    maxParallel: 1
  steps:
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      echo $STACK_ROOT
      mkdir -p ~/.local/bin
      export PATH=$HOME/.local/bin:$PATH;
      etc/scripts/ci-setup.sh
      export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:/opt/happy/1.19.5/bin:/opt/alex/3.1.7/bin:$PATH
    env:
      OS_NAME: ${{ parameters.os }}
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    displayName: 'Installation ${{parameters.os}}'
  - script: |
      curl https://nixos.org/nix/install | sh
      source ~/.profile
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      export PATH=$HOME/.local/bin:$PATH;
      set -ex
      stack install cabal-install
      stack test --flag stack:integration-tests stack:test:stack-integration-test
      set +ex
    displayName: Integration Test
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      export PATH=$HOME/.local/bin:$PATH;
      set -ex
      stack install stack --local-bin-path $(Build.ArtifactStagingDirectory)
      set +ex
    displayName: Gzip Stack
    condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues', 'Failed')
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: stack-linux-x86_64
    condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues', 'Failed')
